# Numpy

In [4]:
import numpy as np

np.__version__ # obtener versión

'1.26.4'

### Creación de arrays numpy

Notas varias: 

- Uso de "deepcopy" para copiar refefrencias -> np.copy
- Tamaño en bytes -> arr1.nbytes()
- Añadir o eliminar un elemento de un implica crearlo de nuevo (pero modificar no)
- Evitar bucles a ser posible

In [ ]:
#Es necesario crear una lista para crear un array numpy (o array n-dimensional)
l = [1,2,3,4,5,6]

np.array(l)

array([1, 2, 3, 4, 5, 6])

In [ ]:
l = [1,2,3,4,5,6]

a1 = np.array(l)
a2 = np.array(l)
a3 = a1

print("Array igual de distinto puntero (is):", a1 is a2)
print("Arrays con mismo puntero (is):", a1 is a3)
print("Arrays con mismo puntero (==):", a1 == a3)

print("Array igual de distinto puntero (equal):", np.arrayequal(a1, a2))

Array igual de distinto puntero (is): False
Arrays con mismo puntero (is): True
Arrays con mismo puntero (==): [ True  True  True  True  True  True]
Array igual de distinto puntero (equal): True


In [12]:
print(np.array([1,2,3,4])) # Creación tradicional
print(np.arange(0,10)) # Array-Range
print(np.zeros(10)) # Array de 10 0's
print(np.ones(10)) # Array de 10 1's
print(np.random.randn(10)) # Array de valores aleatorios
print(np.empty((8,4))) # Array de valores sin inicializar



[1 2 3 4]
[0 1 2 3 4 5 6 7 8 9]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[-0.37758036 -0.19328541 -1.26504494 -1.983526    0.36815575  1.11825821
  0.3866938   0.27157276 -1.30462067  0.39805607]
[[8.63233314e-312 1.05235983e-321 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 5.02034658e+175 6.01354896e-067 9.41671420e-067]
 [3.40921423e-057 4.91605345e-062 1.75935209e-076 1.04915135e-153]
 [6.32299154e+233 6.32672800e+180 2.66371964e+233 1.47762365e+248]
 [1.16096346e-028 2.14027814e+161 4.96212127e+180 1.94919988e-153]
 [2.46447865e+184 1.10818069e-047 6.16880162e-042 1.53378354e-075]
 [1.41528119e+161 1.56602272e-076 1.48340478e-076 1.48242703e-071]
 [4.17921160e-062 1.14484251e+243 2.59903827e-144 4.24969524e-086]]


### Diferencia entre "len" y "size"

Dado un array a1:

reshape ->

In [ ]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
              
print("len:", len(a)) # Tamaño del primer nivel
print("size", np.size(a1)) # Tamaño total 


len: 2
size 6


In [ ]:
m = np.array([[1,2,3], [4,5,6]])

# El bucle solo recorre elementos a un nivel
for i in m:
    print(i)

[1 2 3]
[4 5 6]


### Slicing

In [ ]:
a1 = np.array([[1,2,3], [4,5,6], [7,8,9]])

print(a1[:2]) # Dos primeras en primer nivel
print("------")
print(a1[:2, 1:]) # Dos primeras en primer nivel y una en el segundo
print("------")
print(a1[:, 1:]) # Todo del primer novel y uno del segundo



[[1 2 3]
 [4 5 6]]
------
[[2 3]
 [5 6]]
------
[[2 3]
 [5 6]
 [8 9]]


### Indexing


In [ ]:
a1 = np.array([[1,2,3], [4,5,6], [7,8,9]])

print(a1[[0,2], [0,1]]) # Devuelve lista con elem 0,2 y 0,1

[1 8]


### Operaciones matriciales

In [ ]:
A = np.array([0,1,2,3]).reshape(2,2)
B = np.array([3,2,1,0]).reshape(2,2)

A.dot(B) 

A @ B #Producto de matrices
A.transpose() # Transponer la lista A

# Operaciones con matrices complejas (uso de linalg)
np.linalg.inv(A) #inversa de A

np.linalg.det(A) #determinante

### Otros métdodos importantes

Suponiendo que hay un array a1 y, si es necesario, un array a2:

Propiedades del array:
- a1.shape → dimensiones
- a1.dtype -> tipo de datos
- a1.size -> número total de elementos
- a1.ndim -> número de dimensiones
- a1.itemsize -> bytes por elemento
- a1.nbytes -> memoria total
- len(a1) -> longitud a lo largo del primer eje
  
Transformación y manipulacion:

- a1.reshape(shape) -> cambia la forma (sin modificar datos)
- np.copy(a1) -> copia independiente
- np.append(a1, element, axis) -> añade elementos
- np.delete(a1, index, axis) -> elimina elementos
- a1.astype(tipo) -> convierte el tipo de datos
- np.tile(a1, reps) -> repite el array completo
- np.repeat(a1, reps, axis) -> repite elementos
- a1.transpose() / a1.T / np.transpose(a1) -> transposición

Indexación y filtrado:
- a1[i, j] → acceso a un elemento
- a1[[i1, i2], [j1, j2]] → acceso múltiple
- a1[condición] → filtrado por condición


Operaciones matemáticas y funciones:
- Operaciones (+ - * / **) -> Operación elemento a elemento
- np.round(a1) -> Redondeo de valores
- np.max(a1) -> devuelve el valor máximo
- np.argmax(a1) -> devuelve el índice del valor máximo
- np.std(a1) -> desviación estándar
- np.var(a1) -> varianza


Estadística:
- np.unique(a1) ->Devuelve los valores únicos

# Pandas

In [1]:
import pandas as pd

pd.__version__ # obtener versión

'2.2.2'

Serie: unidimensional 

DataFrame: bidimensional

LECTURA CON PANDAS = pd.read_csv("nombre.csv")

### Creación de objetos con pandas

##### Series

In [2]:

l = [1,2,3,4,5,6]

pd.Series([10, 20, 30, 40], ["red", "green", "blue", "orange"])

red       10
green     20
blue      30
orange    40
dtype: int64

In [6]:
#ALTERNATIVAS PARA CREAR SERIES

print(pd.Series([1, 2, 3, 4])) # Desde lista (similar a np.array)

print(pd.Series(range(0, 5))) # Rango de números (similar a np.arange)

print(pd.Series(np.zeros(5))) # Serie de ceros

print(pd.Series(np.ones(5))) # Serie de unos

print(pd.Series(np.random.randn(5))) # Serie con valores aleatorios

print(pd.Series([None]*5)) # Serie vacía (con NaN) 

0    1
1    2
2    3
3    4
dtype: int64
0    0
1    1
2    2
3    3
4    4
dtype: int64
0    0.0
1    0.0
2    0.0
3    0.0
4    0.0
dtype: float64
0    1.0
1    1.0
2    1.0
3    1.0
4    1.0
dtype: float64
0    1.014547
1   -0.027317
2    0.723940
3    1.699201
4    0.131361
dtype: float64
0    None
1    None
2    None
3    None
4    None
dtype: object


### Métdodos importantes

Propiedades del DataFrame

 - df.shape → dimensiones (filas, columnas)
 - df.columns → nombres de las columnas
 - df.index → índice del DataFrame
 - df.dtypes → tipos de datos de cada columna
 - df.size → número total de elementos
 - df.ndim → número de dimensiones (siempre 2 para DataFrames)
 - len(df) → número de filas
 - df.info() → resumen del DataFrame (tipo de datos, memoria, nulos)
 - df.describe() → estadísticas descriptivas (count, mean, std, min, max, percentiles)
 - df.count(axis) → número de elementos no nulos por eje
 - df.corr() → matriz de correlación entre columnas numéricas

 Transformación y manipulación

- df.copy() → copia independiente
- df.head(n) / df.tail(n) → primeras o últimas n filas
- df.iloc[row_index] / df.loc[label] → acceso a filas por posición o índice
- df.iloc[row_index, col_index] / df.loc[row_label, col_label] → acceso a un elemento
- df[[col1, col2]] → acceso a varias columnas
- df[col] → acceso a una columna (Series)
- df['new_col'] = value → añadir columna (inplace)
- df.drop(labels, axis, inplace=False) → eliminar filas o columnas
- df.rename(columns={}, index={}, inplace=False) → renombrar columnas o índices selectivamente
- df.reset_index(inplace=False) → convertir índice a columna o reiniciar índice
- df.set_index('columna', inplace=False) → establecer columna como índice
- df.sort_values(by=['col'], ascending=True) → ordenar por columna(s)
- df.sort_index(ascending=True) → ordenar por índice
- df.transpose() / df.T → transposición del DataFrame
- df.reindex(new_index, fill_value=NaN) → reindexar filas

Operaciones matemáticas y funciones:

- Operaciones (+ - * /) -> operaciones alineando por índices, NaN si no coincide
- df.apply(func) -> aplicar función a filas/columnas
- df.sum(axis), df.mean(axis, skipna=True) -> suma y media por eje
- df.groupby(['col1', 'col2'])['col3'].mean() -> agrupamiento y cálculo
- df.corrwith(df2) -> correlación entre Series de DataFrames

Lectura y combinación de DataFrames:

- pd.read_csv(ruta) → leer CSV en DataFrame
- pd.concat([df1, df2], axis, sort=False) → concatenar DataFrames
- pd.pivot_table(df, index=[], columns=[], values='', aggfunc=sum, fill_value=NaN) → tabla pivote
- pd.MultiIndex.from_tuples(list_of_tuples) → crear multi-índice
Filtrado y condiciones
- df[condición] → filtrar filas por condición
- df.loc[condición, cols] → filtrar filas y seleccionar columnas

 

In [7]:
dict_data = {'c0':[1,2,3], 'c1':[4,5,6], 'c2':[7,8,9], 'c3':[10,11,12], 'c4':[13,14,15]}
df = pd.DataFrame(dict_data, index=['r0', 'r1', 'r2'])

## Gestión de multiples dataframes

- Inner join -> Devuelve los valores cuyo id está en ambas tablas
- Left/Right join -> obtienes valores nulo filtrando un dato
- Full outer join -> unir todo


pd.merge(dfA, dfB, on="valorUnion" 
how="inner")


pd.merge(dfA)

In [ ]:
dfA = pd.DataFrame({
    'Name':'Harry Potter,David Baker,John Smith,Juan Martinez,Jane Connor'.split(','),
    'Gender':'Male Male Male Male Female'.split(),
    'Age':[23,31,22,36,30]
    
})

dfB = pd.DataFrame({
    'Name':'John Smith,Alex Du Bois,Joanne Rowling,Jane Connor'.split(','),
    'Position':'Intern,Team Lead,Manager,Manager'.split(','),
    'Wage':[25000,75000,90000,70000]
    
})

pd.merge(dfA, dfB,
    on="valorUnion" # Nombre de índice para unir dos palabras (Opcional)
    how="inner" # Tipo de gestión (Opcional)
    )

""" 
Alternativa a on= "valorUnion"
 - on_right= "valor1", on_left=valor2


Alternativas a how="inner"
 - how = "outer"
 - how = "left"
 - how = "right" 

"""


In [ ]:
my_dict = {'Size': list('LLMMMSSSS'),
           'Type': list('AAABBAABB'),
           'Location':[ 'L'+x for x in '111221221'],
           'P1':[1,2,2,3,3,4,5,6,7],
           'P2':[2,4,5,5,6,6,8,9,9]}
my_dict

df = pd.DataFrame(my_dict)

df

pd.pivot_table(df, 
               index = ["Size", "Type"], # Define las filas de la tabla pivote con combinaciones únicas
               columns = "Location", # Define las columnas de la tabla pivote
               values = "P2", # Lista de valores que se esperan como resultado
               aggfunc= "mean",
               fill_value=0
               )

C:\Users\josec\AppData\Local\Temp\ipykernel_17632\442866497.py:12: FutureWarning: The provided callable <function mean at 0x000002C6E874DD00> is currently using DataFrameGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  pd.pivot_table(df,


Location    L1   L2
Size Type          
L    A     3.0  0.0
M    A     5.0  0.0
     B     0.0  5.5
S    A     6.0  8.0
     B     9.0  9.0

- df.count(axis = 0) -> cuenta todos los valores usando como referencia un eje
- df.corr() -> valor de correlación (opt df.column)
df.

# Búsqueda y gestión de datos faltantes

In [ ]:
import seaborn as sns
sns.__version__

'0.13.2'

##### Búsqueda de NaN

In [ ]:
dropna= False
df = sns.load_dataset("titanic")
nan_deck = df["deck"].value_counts(dropna=False) # Incluir NaN en la lista de conteos
print(nan_deck)


deck
NaN    688
C       59
B       47
D       33
E       32
A       15
F       13
G        4
Name: count, dtype: int64


Métodos importantes:
- isnull() -> True si NaN else False
- value_counts() -> 
- dropna(axis = 1, thresh = 500) -> Borra todas las columnas con 500 o más NaN
- df[column].fillna(value) -> rellena todos los valores nulos de la columna con "value"
- ffill() / bfill() -> rellena los NaN con los valores anteriores/posteriores
- idmax() -> devuelve de un set el valor que se repite más veces
- duplicated (subset= None, keep ="first") -> busca duplicados, dejando solo uno (modificar comp con args) (usar con drop)
- drop_duplicates() -> lo de arriba pero para borrar
- s1.astype("category") -> cambia el tipo a categoría (equivalente a ennum) (puedes poner una cat personalizada)
- s1.cut(s1, bins = 3, labels= ["alto", "medio", "bajo"]) -> discreatizar valores continuos en forma de (1, 2], (2,3], (3,4]
- pd.get_dummies(s1, drop_first = True) -> (Pues eso). Drop first permite quitarte una columna que se usa por descarte 

Notas:
- Con Data Feature Engeniering se puede hacer variables Dummy (Aad, regresión lineal)
- Normalizar: Asegurarse de que los valores están entre ciertos límites

In [ ]:
# 1: Filtrado de datos no deseados

# 2: 