## Importar numpy

In [2]:
import numpy as np

np.__version__ # obtener versión

'1.26.4'

## Creación de arrays numpy

Notas varias: 

- Uso de "deepcopy" -> np.copy
- Tamaño en bytes -> arr1.nbytes()

In [ ]:
#Es necesario crear una lista para crear un array numpy (o array n-dimensional)
l = [1,2,3,4,5,6]

np.array(l)

array([1, 2, 3, 4, 5, 6])

In [ ]:
l = [1,2,3,4,5,6]

a1 = np.array(l)
a2 = np.array(l)
a3 = a1

print("Array igual de distinto puntero (is):", a1 is a2)
print("Arrays con mismo puntero (is):", a1 is a3)
print("Arrays con mismo puntero (==):", a1 == a3)

print("Array igual de distinto puntero (equal):", np.arrayequal(a1, a2))

Array igual de distinto puntero (is): False
Arrays con mismo puntero (is): True
Arrays con mismo puntero (==): [ True  True  True  True  True  True]
Array igual de distinto puntero (equal): True


In [ ]:
print(np.array([1,2,3,4])) # Creación tradicional
print(np.arrange(0,10)) # Array-Range
print(np.zeros(10)) # Array de 10 0's
print(np.ones(10)) # Array de 10 1's


## Keyword arguments

- dytpe -> tipo de dato homogeneo (si no puede hace conversión) (bool de "casa" es False) 


## Diferencia entre "len" y "size"

In [ ]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
              
print("len:", len(a)) # Tamaño del primer nivel
print("size", np.size(a1)) # Tamaño total 


len: 2
size 6


In [ ]:
m = np.array([[1,2,3], [4,5,6]])

# El bucle solo recorre elementos a un nivel
for i in m:
    print(i)

[1 2 3]
[4 5 6]
