## Importar numpy

In [1]:
import numpy as np

np.__version__ # obtener versión

'1.26.4'

## Creación de arrays numpy

Notas varias: 

- Uso de "deepcopy" -> np.copy
- Tamaño en bytes -> arr1.nbytes()
- Añadir o eliminar un elemento de un implica crearlo de nuevo (modificar no)

In [ ]:
#Es necesario crear una lista para crear un array numpy (o array n-dimensional)
l = [1,2,3,4,5,6]

np.array(l)

array([1, 2, 3, 4, 5, 6])

In [ ]:
l = [1,2,3,4,5,6]

a1 = np.array(l)
a2 = np.array(l)
a3 = a1

print("Array igual de distinto puntero (is):", a1 is a2)
print("Arrays con mismo puntero (is):", a1 is a3)
print("Arrays con mismo puntero (==):", a1 == a3)

print("Array igual de distinto puntero (equal):", np.arrayequal(a1, a2))

Array igual de distinto puntero (is): False
Arrays con mismo puntero (is): True
Arrays con mismo puntero (==): [ True  True  True  True  True  True]
Array igual de distinto puntero (equal): True


In [4]:
print(np.array([1,2,3,4])) # Creación tradicional
print(np.arange(0,10)) # Array-Range
print(np.zeros(10)) # Array de 10 0's
print(np.ones(10)) # Array de 10 1's
print(np.random.randn(10)) # Array de valores aleatorios



[1 2 3 4]
[0 1 2 3 4 5 6 7 8 9]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[-0.89120095 -0.291598   -0.68249385 -1.46262494 -0.54559388  0.08305436
 -2.61480131 -0.72675623  0.38723496 -0.9470736 ]


## Keyword arguments

- dytpe= X -> tipo de dato homogeneo (si no puede hace conversión) (bool de "casa" es False) 


## Métdodos importantes

Suponiendo que hay un array a1 y, si es necesario, un array a2:

 - np.copy(a1) -> Crea una copia independiente de a1. Los cambios no afectan al original.
 - np.reshape(a1, new_shape)-> Cambia la forma (dimensiones) del array a1 a new_shape. Intenta compartir memoria con el original
 - np.shares_memory(esp_mem1, esp_mem2) ->Devuelve True si esp_mem1 y esp_mem2 comparten la misma memoria interna

## Diferencia entre "len" y "size"

Dado un array a1:

reshape ->

In [ ]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
              
print("len:", len(a)) # Tamaño del primer nivel
print("size", np.size(a1)) # Tamaño total 


len: 2
size 6


In [ ]:
m = np.array([[1,2,3], [4,5,6]])

# El bucle solo recorre elementos a un nivel
for i in m:
    print(i)

[1 2 3]
[4 5 6]
